### ISSUE TITLE
Support complex numbers

### ISSUE THREAD

**Issue by jfcorbett** [startables/startable-standard#11]
Complex numbers should be legal values in table columns. One use case is electrical engineering applications where a complex impedance is needed. Currently, we have to split the real and imaginary parts in two separate columns, which is cumbersome. 

The question is:
 a. Do we simply allow complex numbers in all numerical columns? (as in column `a` below)
 b. Or do we want to explicitly indicate in the column's unit indicator that complex numbers should be expected? (as in column `b` below, where for the sake of argument, the trailing `*` is used here as an example complex flag)
 c. (Or do we not want to deal with complex numbers, and let the user manually split them as in columns `real` and `imag` below?)

```
**foo
all
a         ; b         ; real      ; imag
ohm       ; ohm*      ; ohm       ; ohm
1.3+2.1j  ; 1.3+2.1j  ; 1.3       ; 2.1
42 - 3i   ; 42 - 3i   ; 42        ; -3
```
Pros of `a` (relative to `b`): 
- less burden on the user (no need to type the additional complex flag)
- less pollution of StarTable syntax space (no need to pick a more or less arbitrary complex flag)

Cons of `a` (relative to `b`):
- requires all numerical columns to be tentatively parsed as complex, though in reality only a tiny minority of use cases actually use complex numbers; in the vast majority of cases, the imaginary part will be zero. This may hurt performance. (Though this could be mitigated by parsers having a `real_only=True` option, optimized for reading real numbers more quickly but crashing on complex numbers...)

**Comment by JanusWesenberg** [comment]
Cost of a. would be having to explicitly check against complex types in the 99% of non-complex use cases. Alternative is not just bad performance, but all kinds of issues when you start calling functions that are not defined for complex values such as comparison operators etc. I consider this a no-go.

Main worry about option b is that if this is in the core format, then all readers/writers/editors should ideally implement it? Especially for excel this could be quite a nightmare, since complex values appear to be stored as function calls. But I guess an implementation could just opt out.

My off the cuff response would be to keep it simple and use two columns. But I guess a flagged unit implementation would not hurt anyone. 
- Would a leading star be a more prominent tag?
- Would it make sense to do an Excel POC before including this in the standard.

**Comment by jfcorbett** [comment]
I share your squeamishness about option a. I guess the flow chart of parsers could be: always parse as complex type --> cast to float type in (the 99% of) cases where imaginary part is zero. This would negate the problem of sending complex values into applications and functions designed for floats. Still, conditional typing feels pretty flaky. 

_Would it make sense to do an Excel POC before including this in the standard._
Absolutely, and I did make a little PoC for myself before posting here :-)  The take-home is that, yes, though complex numbers can be created with a formula e.g. `=COMPLEX(42, -666)`, the value stored in the xlsx is of the form `42-666i`, which is perfectly parsable. So, on par with everything else we read from Excel (since [PR#83](https://github.com/startable/pdtable/pull/83) anyway), we would read in the value, not the formula. 

Does this resolve concerns about option b?

(Incidentally, you can also just type `42-666i` in an Excel cell and use complex number formulas such as `IMSUM()` on that, and it will work, so apparently, complex numbers don't _necessarily_ need to be created with formulas.)

Leading star: sure!

**Comment by JanusWesenberg** [comment]
Excellent with the Excel POC. 

One suggstion before we move this forward: In order to make this the least work for reader implementations, could we somehow move the complex mark to the units?  This would 
- remove the need to map between internal and external column names
- keep with the current pattern of having all type information available in unit
-avoid non-alphanumerics in the column name which would be unsupported in the matlab implementation.

Possible formats:

* "functional style with square brackets" `Complex[Ohm]`, `Complex[N/mm2]` 
* "functional style with angle brackets" `Complex<Ohm>`, `Complex[N/mm2]`
* "leading star" `*Ohm`, `*N/mm2`

TBH I am still queasy about this feature, but I guess it would be easy for a reader implementation to provide decent error message if it does not support complext numbers...

**Comment by jfcorbett** [comment]
This is indeed how I sketched it in the OP above. Complex flag on the units.

**Comment by jfcorbett** [comment]
But if we're queasy about it, then perhaps we should refrain. 
In the spirit of conservatism when developing a standard, let's shelve this one for now.
